# Generated by Django 4.2.17 on 2025-01-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['utp', 'role'], name='idx_user_type_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='idx_user_email_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='idx_user_name'),
        ),
        migrations.AddIndex(
            model_name='userpasswordsdictionary',
            index=models.Index(fields=['user', 'valid_from', 'valid_to'], name='idx_pwd_user_dates'),
        ),
        migrations.AddIndex(
            model_name='userpasswordsdictionary',
            index=models.Index(fields=['valid_to', 'user'], name='idx_pwd_validto_user'),
        ),
    ]
