# Generated by Django 4.2.17 on 2025-01-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userpasswordsdictionary',
            name='unique_user_hashed_password',
        ),
    ]
