# Generated by Django 4.2.17 on 2025-01-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='hr.users',
        ),
    ]
