# Generated by Django 4.2.17 on 2025-01-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='error_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
