# Generated by Django 4.2.17 on 2025-01-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accpermission',
            table='sec.acc_permission',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='sec.audit_log',
        ),
        migrations.AlterModelTable(
            name='changelog',
            table='sec.change_log',
        ),
        migrations.AlterModelTable(
            name='client',
            table='hr.u_client',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='hr.u_employee',
        ),
        migrations.AlterModelTable(
            name='errorlog',
            table='sec.error_log',
        ),
        migrations.AlterModelTable(
            name='user',
            table='hr.u_user',
        ),
        migrations.AlterModelTable(
            name='userloginaudit',
            table='sec.user_login_audit',
        ),
        migrations.AlterModelTable(
            name='userpasswordsdictionary',
            table='sec.u_user_passwords_dictionary',
        ),
    ]
