# Generated by Django 4.2.17 on 2025-01-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_errorlog_error_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpasswordsdictionary',
            table='sec.user_passwords_dictionary',
        ),
    ]
