# Generated by Django 4.2.17 on 2025-01-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpasswordsdictionary_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='social_security',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.accpermission'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_security',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accpermission',
            name='perm_level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Admin'), (2, 'Manager'), (3, 'Funcionário')]),
        ),
    ]
