# Generated by Django 4.2.17 on 2025-01-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_employee_role_remove_employee_social_security_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_security',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
