# Generated by Django 5.1.1 on 2024-11-05 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emission_date', models.DateField(default=django.utils.timezone.now)),
                ('billing_date', models.DateField()),
                ('invoice_status', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.user')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reservation.reservation')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.paymentmethod')),
            ],
            options={
                'db_table': 'invoice',
                'constraints': [models.CheckConstraint(condition=models.Q(('invoice_status__in', [True, False])), name='ck_invoice_status')],
            },
        ),
    ]
