# Generated by Django 5.1.1 on 2024-11-12 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emission_date', models.DateField(default=django.utils.timezone.now)),
                ('billing_date', models.DateField()),
                ('invoice_status', models.BooleanField()),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
    ]
