# Generated by Django 4.2.17 on 2025-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_date',
            field=models.DateField(null=True),
        ),
    ]
