# Generated by Django 4.2.17 on 2025-01-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['emission_date', 'billing_date'], name='idx_invoice_dates'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_status', 'payment_method'], name='idx_invoice_status_method'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'emission_date'], name='idx_invoice_client_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['reservation', 'invoice_status'], name='idx_invoice_res_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'payment_method'], name='idx_payment_date_method'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='idx_payment_invoice_date'),
        ),
    ]
