# Generated by Django 4.2.17 on 2025-01-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='finance.invoice',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='finance.payments',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='finance.payment_method',
        ),
    ]
