# Generated by Django 5.1.1 on 2024-12-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_guests', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Performance Overview',
                'verbose_name_plural': 'Performance Overviews',
            },
        ),
        migrations.CreateModel(
            name='SalesOverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Sales Over Time',
                'verbose_name_plural': 'Sales Over Time',
            },
        ),
        migrations.CreateModel(
            name='TopPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Top Placement',
                'verbose_name_plural': 'Top Placements',
            },
        ),
    ]
