# Generated by Django 5.1.4 on 2024-12-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceOverview',
        ),
        migrations.DeleteModel(
            name='SalesOverTime',
        ),
        migrations.DeleteModel(
            name='TopPlacement',
        ),
    ]
