# Generated by Django 5.1.1 on 2024-12-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceOverview',
        ),
        migrations.DeleteModel(
            name='SalesOverTime',
        ),
        migrations.DeleteModel(
            name='TopPlacement',
        ),
    ]
