# Generated by Django 4.2.17 on 2025-01-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commodity',
            table='room_management.commodity',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='management.hotel',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room_management.room',
        ),
        migrations.AlterModelTable(
            name='roomcommodity',
            table='room_management.room_commodity',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='room_management.room_type',
        ),
    ]
