# Generated by Django 4.2.17 on 2025-01-11 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_management', '0003_commodity_hotel_hotelemployees_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelemployees',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelemployees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelemployees',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeshotel', to='hotel_management.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='roomcommodity',
            unique_together={('room', 'commodity')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'room_number')},
        ),
    ]
