# Generated by Django 4.2.17 on 2025-01-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_management', '0003_commodity_hotel_alter_roomtype_table_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelemployees', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeshotel', to='hotel_management.hotel')),
            ],
            options={
                'db_table': 'management.hotel_employee',
            },
        ),
    ]
