# Generated by Django 4.2.17 on 2025-01-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0003_commodity_hotel_room_roomcommodity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomtype',
            table='room_management.room_types',
        ),
    ]
