# Generated by Django 4.2.17 on 2025-01-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_management', '0003_commodity_hotel_hotelemployees_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cc_pass', models.CharField(max_length=20, verbose_name='CC or Passport')),
                ('phone', models.CharField(max_length=20)),
                ('full_address', models.CharField(max_length=160, null=True)),
                ('postal_code', models.CharField(max_length=8, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'reserves.guest',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected'), ('CC', 'Canceled'), ('CI', 'Checked In'), ('CO', 'Checked Out')], default='P', max_length=2, verbose_name='Reservation Status')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'reserves.reservation',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive', models.TextField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'MidLow'), ('F', 'Festival')])),
                ('begin_month', models.IntegerField()),
                ('begin_day', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Season Rate')),
            ],
            options={
                'db_table': 'finance.season',
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_reservation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='reservation.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='hotel_management.room')),
            ],
            options={
                'db_table': 'reserves.room_reservation',
            },
        ),
    ]
