# Generated by Django 5.1.1 on 2024-12-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS FINANCE"),
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS RESERVES"),
    ]
