# Generated by Django 4.2.17 on 2025-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected'), ('CC', 'Canceled'), ('CI', 'Checked In'), ('CO', 'Checked Out')], default='P', max_length=2, verbose_name='Reservation Status'),
        ),
    ]
