# Generated by Django 4.2.17 on 2025-01-08 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.season'),
        ),
        migrations.AddField(
            model_name='guest',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservation.reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('reservation', 'room')},
        ),
    ]
