# Generated by Django 4.2.17 on 2025-01-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='',
        ),
    ]
