# Generated by Django 5.1.1 on 2024-12-02 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_management', '0002_initial'),
        ('reservation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservation.reservation'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='reservation.reservation'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='hotel_management.room'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('descriptive', 'begin_date', 'end_date')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.season'),
        ),
        migrations.AddField(
            model_name='priceperseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_prices', to='reservation.season'),
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('reservation', 'room')},
        ),
    ]
