# Generated by Django 5.1.1 on 2024-12-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Season Rate'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('descriptive', 'begin_date', 'end_date', 'rate')},
        ),
        migrations.DeleteModel(
            name='PricePerSeason',
        ),
    ]
