# Generated by Django 4.2.17 on 2025-01-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reserves.reservation',
        ),
    ]
