# Generated by Django 5.1.1 on 2025-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_season_unique_together_season_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='descriptive',
            field=models.CharField(choices=[('A', 'High'), ('B', 'Low'), ('F', 'Festival')], max_length=255, verbose_name='Season Type'),
        ),
    ]
