# Generated by Django 4.2.17 on 2025-01-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_season_descriptive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='descriptive',
            field=models.TextField(),
        ),
    ]
