# Generated by Django 4.2.17 on 2025-01-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_season_descriptive'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guest',
            table='reserves.guest',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reserves.reservation',
        ),
        migrations.AlterModelTable(
            name='roomreservation',
            table='reserves.room_reservation',
        ),
        migrations.AlterModelTable(
            name='season',
            table='finance.season',
        ),
    ]
